const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    CLEAR_CART: 'CLEAR_CART',
}
export default CartActionTypes